### ISSUE TITLE
Torches should not block water and lava flow.

### ISSUE THREAD

**Issue by matshou** [yooksi/FierySouls#1]
When placed on the source of water or lava flow (the block from which the liquid emerges) it blocks the flow as it replaces the source and the rest of the water or lava dissipates.

_Update:_ this seems to be the problem with vanilla torches as well.

**Comment by yooksi** [comment]
This seems to be a problem with vanilla torches as well...

**Comment by yooksi** [comment]
Enhancement implemented with e27a7038a22d61aa19c4ca2f22038f04003d0e79

**Comment by matshou** [comment]
Enhancement implemented with commit e27a7038a22d61aa19c4ca2f22038f04003d0e79.

**Comment by matshou** [comment]
The issue was not completely resolved, we need to apply a patch.

**Comment by matshou** [comment]
Should be resolved with commit 7322f9fc04c3315fca7e17490db5213dfedde19a
